# Generated by Django 4.2 on 2023-09-14 21:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('shop_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_logout', models.DateTimeField(null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to='photos/')),
                ('number_of_spots', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Workdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kurumsal.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailing', models.BooleanField(default=False)),
                ('detailing_price', models.FloatField()),
                ('waterless', models.BooleanField(default=False)),
                ('waterless_price', models.FloatField()),
                ('pressurized', models.BooleanField(default=False)),
                ('pressurized_price', models.FloatField()),
                ('steam', models.BooleanField(default=False)),
                ('steam_price', models.FloatField()),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kurumsal.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('profile_photo', models.ImageField(null=True, upload_to='photos/')),
                ('website', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=55, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('neighbourhood', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('opening_hour', models.TimeField(null=True)),
                ('closing_hour', models.TimeField(null=True)),
                ('closed', models.BooleanField(default=False)),
                ('number_of_spots', models.IntegerField(default=1)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kurumsal.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150, null=True)),
                ('shop_profile_photo', models.CharField(max_length=150, null=True)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=5)),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurumsal.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotedShops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=55)),
                ('district', models.CharField(max_length=100, null=True)),
                ('neighbourhood', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2023, 9, 21, 21, 19, 36, 207547, tzinfo=datetime.timezone.utc))),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurumsal.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurumsal.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurumsal.shop')),
            ],
        ),
        migrations.CreateModel(
            name='NoAvailableSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=5)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurumsal.shop')),
            ],
        ),
    ]
