# Generated by Django 4.2.2 on 2023-09-16 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedshops',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 14, 26, 26, 422625, tzinfo=datetime.timezone.utc)),
        ),
    ]
