# Generated by Django 4.2.2 on 2023-09-16 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0002_alter_promotedshops_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedshops',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 14, 27, 6, 635077, tzinfo=datetime.timezone.utc)),
        ),
    ]
