# Generated by Django 4.2.2 on 2023-09-16 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0005_alter_promotedshops_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedshops',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 15, 33, 26, 983983, tzinfo=datetime.timezone.utc)),
        ),
    ]
