# Generated by Django 4.2 on 2023-09-18 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0007_alter_promotedshops_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedshops',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 12, 8, 55, 955542, tzinfo=datetime.timezone.utc)),
        ),
    ]
