# Generated by Django 4.2 on 2023-09-18 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0009_alter_promotedshops_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedshops',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 12, 26, 2, 336746, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
