# Generated by Django 4.2 on 2023-09-18 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0010_alter_promotedshops_expiry_date_alter_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedshops',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 12, 47, 7, 872678, tzinfo=datetime.timezone.utc)),
        ),
    ]
