# Generated by Django 4.2 on 2023-09-18 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0011_alter_promotedshops_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedshops',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 14, 4, 11, 76180, tzinfo=datetime.timezone.utc)),
        ),
    ]
