# Generated by Django 4.2 on 2023-09-18 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0012_alter_promotedshops_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='owner_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='promotedshops',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 14, 39, 2, 492087, tzinfo=datetime.timezone.utc)),
        ),
    ]
